---
kind: pipeline
type: docker
name: api

platform:
  os: linux
  arch: amd64

steps:
  - name: api_changes_only
    image: alpine/git
    commands:
      - if (git diff --exit-code $DRONE_COMMIT_BEFORE $DRONE_COMMIT_AFTER -- api); then exit 78; fi

  - name: build_push_image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: robbymilo/backcountrydata
      tags: latest
      dockerfile: api/Dockerfile

trigger:
  event:
  - push
  branch:
  - master
