---
kind: pipeline
type: docker
name: api

platform:
  os: linux
  arch: amd64

steps:
  - name: api_only
    image: alpine/git
    commands:
      - if (git diff --exit-code $(git rev-parse --short "HEAD^") $(git rev-parse --short HEAD) -- api); then exit 78; fi

  - name: build_push_image
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: robbymilo/backcountrydata
      tags: latest
      dockerfile: api/Dockerfile

trigger:
  event:
  - push
  branch:
  - master

---
kind: pipeline
type: docker
name: frontend

platform:
  os: linux
  arch: amd64

steps:
  - name: frontend_only
    image: alpine/git
    commands:
      - if (git diff --exit-code $(git rev-parse --short "HEAD^") $(git rev-parse --short HEAD) -- frontend); then exit 78; fi

  - name: build__deploy_frontend
    image: robbymilo/node-netlify
    environment:
      TOKEN:
        from_secret: drone-netlify-token
    commands:
      - make build-frontend
      - netlify deploy --dir dist --site c227ef54-b0f6-434b-9c19-7db3ff8e416c --auth $TOKEN --prod

trigger:
  event:
  - push
  branch:
  - master
