---
kind: pipeline
type: docker
name: website

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    settings:
      repo: robbymilo/backcountrydata
      dockerfile: api/Dockerfile

trigger:
  event:
  - push
  branch:
  - master
