---
kind: pipeline
type: docker
name: website

platform:
  os: linux
  arch: amd64

steps:
  - name: docker
    image: plugins/docker
    environment:
      USERNAME:
        from_secret: docker_username
      PASSWORD:
        from_secret: docker_password
    repo: robbymilo/backcountrydata
    username: ${USERNAME}
    password: ${PASSWORD}
    settings:
      dockerfile: api/Dockerfile

trigger:
  event:
  - push
  branch:
  - master
