---
kind: pipeline
type: docker
name: website

platform:
  os: linux
  arch: amd64

steps:
  - name: docker  
    image: plugins/docker
    settings:
      repo: backcountrydata/api
      dockerfile: api/Dockerfile

trigger:
  event:
  - push